---
- name: "Install EPEL and deltarpm"
  package:
    name: "{{ item.name }}"
    state: latest
    update_cache: yes
  with_items:
    - { name: "epel-release", distribution: ["CentOS"] }
    - { name: "deltarpm", distribution: ["CentOS", "Amazon"] }
    - { name: "yum-utils", distribution: ["CentOS", "Amazon"] }
  when: hostvars[inventory_hostname]["ansible_distribution"] in item.distribution

- name: "Install base packages"
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - "htop"
    - "screen"
    - "vim"
    - "bash-completion"

- name: "Install base packages (Centos 7)"
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - "bash-completion-extras"
  when: hostvars[inventory_hostname]["ansible_distribution_major_version"] == "7"
